apiVersion: ingressnodefirewall.openshift.io/v1alpha1
kind: IngressNodeFirewall
metadata:
  name: ingressnodefirewall
spec:
  ingress:
    - rules:
        - action: Deny
          order: 10
          protocolConfig:
            protocol: TCP
            tcp:
              ports: 22
      sourceCIDRs:
        - 0.0.0.0/0
  interfaces:
    - ens33
  nodeSelector:
    matchLabels:
      edge.io/firewall: 'true'
